name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg for paulo-pires
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: paulo-pires
          outputs: dist/snake.svg?palette=github&color_mode=dark
          
      - name: generate snake.svg with a second color palette
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: paulo-pires
          outputs: dist/snake-alt.svg?palette=gruvbox

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
